//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.PracticeAppointments = new HashSet<PracticeAppointment>();
        }
    
        public int AppointmentId { get; set; }
        public int PatientId { get; set; }
        public int MedicalOrderId { get; set; }
        public Nullable<decimal> Plus { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int State { get; set; }
    
        public virtual MedicalOrder MedicalOrder { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PracticeAppointment> PracticeAppointments { get; set; }
    }
}
