//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthInsuranceProvider
    {
        public HealthInsuranceProvider()
        {
            this.HealthInsuranceProviderPlans = new HashSet<HealthInsuranceProviderPlan>();
            this.Orders = new HashSet<Order>();
        }
    
        public int HealthInsuranceProviderId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal NBU { get; set; }
    
        public virtual ICollection<HealthInsuranceProviderPlan> HealthInsuranceProviderPlans { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
