//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOrder
    {
        public MedicalOrder()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int MedicalOrderId { get; set; }
        public int HealthInsuranceProviderPlanId { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> NBU { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual HealthInsuranceProviderPlan HealthInsuranceProviderPlan { get; set; }
    }
}
