//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.PracticeOrders = new HashSet<PracticeOrder>();
        }
    
        public int OrderId { get; set; }
        public int HealthInsuranceProviderId { get; set; }
        public int OrderNumber { get; set; }
        public string PatientName { get; set; }
        public System.DateTime AttentionDate { get; set; }
        public Nullable<int> PatientDNI { get; set; }
        public Nullable<System.DateTime> PatientBirthDate { get; set; }
    
        public virtual HealthInsuranceProvider HealthInsuranceProvider { get; set; }
        public virtual ICollection<PracticeOrder> PracticeOrders { get; set; }
    }
}
