//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalImage
    {
        public string ProfessionalId { get; set; }
        public byte[] ProfileImage { get; set; }
    
        public virtual Professional Professional { get; set; }
    }
}
