//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPaymentSummary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Professionals = new HashSet<Professional>();
        }
    
        public int ProvinceId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Professional> Professionals { get; set; }
    }
}
